### ISSUE TITLE
@tkrd さんの Local環境でテストができない件

### ISSUE THREAD

**Issue by jinmayamashita** [shizuoka-dev/kuikka#11]
local環境で確認するのに設定が足りないところがあるので、
READMEとSlackの設定ファイルの更新が必要。:eyes:

_Originally posted by @jinmayamashita in https://github.com/shizuoka-dev/kuikka/pull/9/comment#issuecomment-437674638_

**Comment by TKRD7** [comment]
#12 
私の環境においても、ローカル環境で確認できるようになりました。
