### ISSUE TITLE
Contributing Guidelines が必要

### ISSUE THREAD

**Issue by jinmayamashita** [shizuoka-dev/kuikka#2]
kuikka contributors が Issue の作成、PR する際に参考になる Guidelines が必要。
改善方法として `README`、`PULL_REQUEST_TEMPLATE.md`、`ISSUE_TEMPLATE.md`を作成

- [x] PULL_REQUEST_TEMPLATE.md 作成
- [x] ISSUE_TEMPLATE.md 作成
- [x] README 改善

例：[React](https://github.com/facebook/react#contributing)
<img width="1048" alt="screenshot 2018-10-27 at 13 06 57" src="https://user-images.githubusercontent.com/9401060/47599468-b4479e80-d9e9-11e8-8601-fffb7083a408.png">

**Comment by TKRD7** [comment]
#5 ガイドラインの作成を確認。ドキュメント内容の確認も併せて実施。
